# Generated by Django 2.2.8 on 2021-05-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30, unique=True)),
                ('producer', models.CharField(max_length=30)),
                ('release_date', models.CharField(max_length=10)),
                ('rt_score', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('data_nasc', models.DateField()),
            ],
        ),
    ]
